appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: !secret http_url
      token: !secret http_token

log:                                            
  accessfile: /conf/logs/appdaemon-access.log
  errorfile: /conf/logs/appdaemon-error.log
  logfile: /conf/logs/appdaemon.log
  log_generations: 3
  log_size: 1000000
