---
squeezeboxplayer:
  module: squeezebox
  class: Squeezebox
  verbose_log: true
  server: !secret squeeze_host
  port: !secret squeeze_port
  player: 'bb:bb:c8:f3:04:34'
  config_dir: "/confhass/"
  hass_url: !secret hass_url
