---
alerte_meteo:
  module: weather_alert
  class: VigilanceMeteoFrance
  departement: "06"
  run_every: 15
  phone_numbers:
    - !secret phone_number_1
  verbose_log: true
  db_file: "/conf/apps/database.db"
  switch_activate: input_boolean.enable_weather_alert_notif
