version: '3.1'

services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-test
    restart: unless-stopped
    ports:
      - "59883:1883"
      - "59001:9001"
    volumes:
      - /srv/data/butler/docker-test/mosquitto:/mosquitto/data
      - /srv/data/butler/docker-test/mosquitto.conf:/mosquitto/config/mosquitto.conf
    logging:
      options:
        max-size: 10m

  homeassistant_main:
    container_name: hass-main
    image: homeassistant/home-assistant:0.86.1
    restart: unless-stopped
    ports:
      - "59123:8123"
    volumes:
      - /srv/data/butler/docker-test/hass-main:/config
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 10m
    depends_on:
      - mosquitto
      - homeassistant_zwave

  homeassistant_zwave:
    container_name: hass-zwave
    image: homeassistant/home-assistant:0.86.1
    restart: unless-stopped
    ports:
      - "59124:8123"
    volumes:
      - /srv/data/butler/docker-test/hass-zwave:/config
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 10m
    depends_on:
      - mosquitto
