---

# OREGON
"sensor.oregon*_temp":
  friendly_name: Température
"sensor.oregon*_hum":
  friendly_name: Humidité
"sensor.oregon*_hstatus":
  friendly_name: Statut
"sensor.oregon*_bat":
  friendly_name: Batterie

# QUBINO WIRE PILOT
"binary_sensor.qubino_pilot_*":
  hidden: true
"light.qubino_pilot_*_level*":
  hidden: true
"sensor.qubino_pilot_*":
  hidden: true
"switch.qubino_pilot_*_switch*":
  hidden: true

# FIBARO ROLLER SHUTTER
"sensor.fibaro_roller_shutter_*":
  hidden: true

# PLUG Neo CoolCam
"sensor.prise_neocoolcam_*alarm_level*":
  hidden: true
"sensor.prise_neocoolcam_*alarm_type*":
  hidden: true
"sensor.prise_neocoolcam_*current*":
  hidden: true
"sensor.prise_neocoolcam_*exporting*":
  hidden: true
"sensor.prise_neocoolcam_*interval*":
  hidden: true
"sensor.prise_neocoolcam_*power_management*":
  hidden: true
"sensor.prise_neocoolcam_*previous_reading*":
  hidden: true
"sensor.prise_neocoolcam_*sourcenodeid*":
  hidden: true
"sensor.prise_neocoolcam_*voltage*":
  hidden: true
"sensor.prise_neocoolcam_*power*":
  friendly_name: Puissance
"sensor.prise_neocoolcam_*energy*":
  friendly_name: Consommation

# FIBARO MOTION SENSOR
"binary_sensor.fibaro_motion_*_sensor":
  friendly_name: Présence
"sensor.fibaro_motion_*_temperature*":
  friendly_name: Température
"sensor.fibaro_motion_*_luminance*":
  friendly_name: Luminosité
"sensor.fibaro_motion_*_alarm*":
  hidden: true
"sensor.fibaro_motion_*_burglar*":
  hidden: true
"sensor.fibaro_motion_*_general*":
  hidden: true
"sensor.fibaro_motion_*_sourcenodeid*":
  hidden: true
"sensor.fibaro_motion_*_seismic_intensity*":
  hidden: true
  friendly_name: Sismic

# FIBARO DIMMER
"sensor.fibaro_dimmer_*_alarm_level*":
  hidden: true
"sensor.fibaro_dimmer_*_alarm_type*":
  hidden: true
"sensor.fibaro_dimmer_*_exporting*":
  hidden: true
"sensor.fibaro_dimmer_*_heat*":
  hidden: true
"sensor.fibaro_dimmer_*_power_management*":
  hidden: true
"sensor.fibaro_dimmer_*_sourcenodeid*":
  hidden: true
"sensor.fibaro_dimmer_*_system*":
  hidden: true
"sensor.fibaro_dimmer_*_power_2":
  hidden: true
"sensor.fibaro_dimmer_*_power":
  friendly_name: Puissance
"sensor.fibaro_dimmer_*_energy*":
  friendly_name: Consommation
"light.fibaro_dimmer_*_level_2":
  hidden: true
