
######################################################
## Views

default_view:
#Home:
  name: Maison
  view: yes
  icon: mdi:home
  entities:
  - persistent_notification.1
  - group.calendar
  - group.household
  - group.thermostat_home
  - group.volets_rdc
  - group.lumieres
  - group.interrupteurs
  - group.ConsommationMaison

RdC:
  name: Rez de chaussée
  view: yes
  icon: mdi:sofa
  entities:
  - remote.salon
  - group.lumieres_rdc
  - group.volets_rdc
  - group.thermometersalon
  - group.FibaroEyeEtage
  - group.FibaroEyeSaM
  - sensor.pied_delephant
  - sensor.non_definie

Etage:
  name: Etage
  view: yes
  icon: mdi:hotel
  entities:
  - group.lumieres_etage
  - group.thermometerparents
  - group.thermometerthea
  - group.thermometerbureau
  - group.salledebain

Thermostat:
  name: Thermostats
  view: yes
  icon: mdi:thermometer-lines
  entities:
  - group.thermostat_home
  - group.thermostat_rdc
  - group.thermostat_parents
  - group.thermostat_thea

HiFi:
  view: yes
  name: Audio/Vidéo
  icon: mdi:play-circle-outline
  entities:
  - group.tv
  - media_player.plex_mi_box
  - media_player.mi_speaker_wifi

WeatherDashboard:
  view: yes
  name: Météo
  icon: mdi:weather-partlycloudy
  entities:
  - group.weather
  - group.WeatherAlert
  - weather.yweather
  - group.thermometerjardin

Cameras:
  name: Cameras
  view: yes
  icon: mdi:cctv
  entities:
  - group.interior_cameras

Equipements:
  view: yes
  name: Equipements
  icon: mdi:server-security
  entities:
  - group.system
  - group.servershealth
  # - group.batteries
  - group.InfoLumiereSalleManger
  - group.InfoLumiereSalon
  - group.InfoLumiereEntree
  - group.InfoLumiereEscalier
  - group.InfoLumiereSalleDeBain
  - group.InfoLumiereBureau
  - group.InfoLumiereChThea
  - group.InfoLumiereChParents
  - group.InfoPriseTVHiFi
  - group.InfoPriseTest

Automations:
  view: yes
  name: Automatismes
  icon: mdi:home-automation
  control: hidden
  entities:
  - group.automationscontrol
  - group.all_automations

################################################################
## Groups

Calendar:
  name: Calendriers
  entities:
  - sensor.date__time
  - sensor.calendar_next_text
  - sensor.calendar_next_time

Household:
  name: Présence
  entities:
  - device_tracker.iphone_olivier
  - device_tracker.iphone_sandrine
  - device_tracker.iphone_thea

Lumieres:
  name: Lumières
  entities:
  - light.fibaro_dimmer_bureau_level
  - light.fibaro_dimmer_entree_level
  - light.fibaro_dimmer_escalier_level
  - light.fibaro_dimmer_parents_level
  - light.fibaro_dimmer_salle_a_manger_level
  - light.fibaro_dimmer_salledebain_level
  - light.fibaro_dimmer_salon_level
  - light.fibaro_dimmer_thea_level

Interrupteurs:
  name: Interrupteurs
  entities:
  - switch.prise_neocoolcam_tvhifi_switch
  - switch.sonoff_garageportail
  - switch.sonoff_salon
  - switch.sonoff_jardin_1
  - switch.prise_neocoolcam_switch
  - switch.comfee

Thermostat_Home:
  name: Thermostat
  entities:
  - input_select.thermostat_mode

Volets_RDC:
  name: Volets
  entities:
  - cover.fibaro_roller_shutter_cuisine_level
  - cover.fibaro_roller_shutter_salon_level
  - cover.fibaro_roller_shutter_salle_a_manger_level
  
Thermostat_RDC:
  name: Thermostat
  entities:
  - sensor.oregontemp_2340_temp
  - input_number.thermostat_rdc
  - input_number.thermostat_consigne_rdc
  - input_select.radiator_salon
  - input_select.radiator_sallemanger

Lumieres_RDC:
  name: Lumières
  entities:
  - light.fibaro_dimmer_entree_level
  - light.fibaro_dimmer_salon_level
  - light.fibaro_dimmer_salle_a_manger_level

Thermostat_Parents:
  name: Chambre Parents
  entities:
  - sensor.oregontemphygro_5288a_temp
  - input_number.thermostat_parents
  - input_number.thermostat_consigne_parents
  - input_select.radiator_parents

Thermostat_Thea:
  name: Chambre Théa
  entities:
  - sensor.oregontemphygro_628da_temp
  - input_number.thermostat_thea
  - input_number.thermostat_consigne_thea
  - input_select.radiator_thea

Lumieres_Etage:
  name: Lumières
  entities:
  - light.fibaro_dimmer_escalier_level
  - light.fibaro_dimmer_salledebain_level
  - light.fibaro_dimmer_bureau_level
  - light.fibaro_dimmer_parents_level
  - light.fibaro_dimmer_thea_level

Weather:
  name: Météo
  entities:
  - sun.sun
  - sensor.moon
  - sensor.auribeausursiagne_temperature
  - sensor.auribeausursiagne_weather
  - sensor.auribeausursiagne_wind_speed
  - sensor.auribeausursiagne_uv
  - sensor.auribeausursiagne_rain_chance
  - sensor.auribeausursiagne_thunder_chance
  - sensor.auribeausursiagne_snow_chance
  - sensor.auribeausursiagne_freeze_chance

System:
  name: Système
  entities:
  - updater.updater
  - sensor.date__time
  - sensor.uptime

ServersHealth:
  name: Equipements
  entities:
  - binary_sensor.broadlink_rm_pro
  - binary_sensor.camera_salon
  - binary_sensor.esxi
  - binary_sensor.imprimante
  - binary_sensor.livebox
  - binary_sensor.mi_3_android_tv
  - binary_sensor.mi_speaker_network
  - binary_sensor.nginx
  - binary_sensor.open_media_vault
  - binary_sensor.pfsense
  - binary_sensor.tplink_archer_c7
  - binary_sensor.tplink_wa830re
  
TV:
  name: TV/Vidéo
  entities:
  - remote.salon
  - sensor.plex

WeatherAlert:
  name: Vigilance Météo
  control: hidden
  entities:
  - sensor.alerte_crue
  - sensor.alerte_vigilance
  - sensor.alerte_risques

Batteries:
  control: hidden
  name: Batteries
  entities:
  - sensor.oregontemp_2340_bat
  - sensor.oregontemphygro_2d0a_bat
  - sensor.oregontemphygro_5288a_bat
  - sensor.oregontemphygro_628da_bat
  - sensor.oregontemphygro_728f5_bat

AutomationsControl:
  control: hidden
  name: Automatismes
  entities:
  - input_boolean.enable_covers_sunrise
  - input_boolean.enable_covers_sunset
  - input_boolean.enable_weather_alert_notif
  - input_boolean.enable_light_garage
  - input_boolean.enable_garden_fountain
  - input_boolean.enable_garden_projector
  - input_boolean.enable_mosquito_switch
  - input_boolean.enable_pool_pump
  - input_boolean.enable_christmas_decoration

#BackyardCameras:

Interior Cameras:
  - camera.rez_de_chaussee


##################################################################################


SalledeBain:
  control: hidden
  name: Salle de bain
  entities:
    - sensor.salle_de_bain

ThermometerBureau:
  control: hidden
  name: Bureau
  entities:
    - sensor.oregontemphygro_728f5_temp
    - sensor.oregontemphygro_728f5_hum
    - sensor.oregontemphygro_728f5_hstatus
    - sensor.oregontemphygro_728f5_bat

ThermometerParents:
  control: hidden
  name: Chambre des Parents
  entities:
    - sensor.oregontemphygro_5288a_temp
    - sensor.oregontemphygro_5288a_hum
    - sensor.oregontemphygro_5288a_hstatus
    - sensor.oregontemphygro_5288a_bat
  
ThermometerThea:
  control: hidden
  name: Théa
  entities:
    - sensor.oregontemphygro_628da_temp
    - sensor.oregontemphygro_628da_hum
    - sensor.oregontemphygro_628da_hstatus
    - sensor.oregontemphygro_628da_bat
  
ThermometerSalon:
  control: hidden
  name: Salon
  entities:
    - sensor.oregontemp_2340_temp
    - sensor.oregontemp_2340_bat

ThermometerJardin:
  control: hidden
  name: Jardin
  entities:
    - sensor.oregontemphygro_2d0a_temp
    - sensor.oregontemphygro_2d0a_hum
    - sensor.oregontemphygro_2d0a_hstatus
    - sensor.oregontemphygro_2d0a_bat

FibaroEyeEtage:
  control: hidden
  name: Etage
  entities:
    - binary_sensor.fibaro_motion_etage_sensor
    - sensor.fibaro_motion_etage_temperature
    - sensor.fibaro_motion_etage_luminance

FibaroEyeSaM:
  control: hidden
  name: Salle à Manger
  entities:
    - binary_sensor.fibaro_motion_salle_a_manger_sensor
    - sensor.fibaro_motion_salle_a_manger_temperature
    - sensor.fibaro_motion_salle_a_manger_luminance

InfoPriseTest:
  control: hidden
  entities:
  - sensor.prise_neocoolcam_power
  - sensor.prise_neocoolcam_energy

InfoPriseTVHiFi:
  control: hidden
  entities:
  - sensor.prise_neocoolcam_tvhifi_power
  - sensor.prise_neocoolcam_tvhifi_energy

InfoLumiereChParents:
  control: hidden
  entities:
  - sensor.fibaro_dimmer_parents_power
  - sensor.fibaro_dimmer_parents_energy

InfoLumiereChThea:
  control: hidden
  entities:
  - sensor.fibaro_dimmer_thea_power
  - sensor.fibaro_dimmer_thea_energy

InfoLumiereBureau:
  control: hidden
  entities:
  - sensor.fibaro_dimmer_bureau_power
  - sensor.fibaro_dimmer_bureau_energy

InfoLumiereSalleDeBain:
  control: hidden
  entities:
  - sensor.fibaro_dimmer_salledebain_power
  - sensor.fibaro_dimmer_salledebain_energy

InfoLumiereEscalier:
  control: hidden
  entities:
  - sensor.fibaro_dimmer_escalier_power
  - sensor.fibaro_dimmer_escalier_energy

InfoLumiereEntree:
  control: hidden
  entities:
  - sensor.fibaro_dimmer_entree_power
  - sensor.fibaro_dimmer_entree_energy

InfoLumiereSalon:
  control: hidden
  entities:
  - sensor.fibaro_dimmer_salon_power
  - sensor.fibaro_dimmer_salon_energy

InfoLumiereSalleManger:
  control: hidden
  entities:
  - sensor.fibaro_dimmer_salle_a_manger_power
  - sensor.fibaro_dimmer_salle_a_manger_energy

ConsommationMaison:
  control: hidden
  name: Consommation
  entities:
  - sensor.qubino_zmnhtdx_smart_meter_s4_s5_s6_voltage
  - sensor.qubino_zmnhtdx_smart_meter_s4_s5_s6_current
  - sensor.qubino_zmnhtdx_smart_meter_s4_s5_s6_power
  - sensor.qubino_zmnhtdx_smart_meter_s4_s5_s6_energy_2
