---
host: !secret influxdb_host
port: !secret influxdb_port
database: !secret influxdb_db
username: !secret influxdb_username
password: !secret influxdb_password
max_retries: 3
default_measurement: state
exclude:
  domains:
    - sun
    - zwave
    - media_player
    - logger

