---

########################################################################################
## themostat - base temperature value
## thermostat_consigne - current requested value depending on the time (-2,-1,+0 vs base)

thermostat_rdc:
  name: Confort
  min: 15
  max: 25
  step: 1
  mode: box
  unit_of_measurement: "°"
  icon: mdi:thermometer

thermostat_consigne_rdc:
  name: Consigne
  min: 15
  max: 25
  step: 1
  mode: box
  unit_of_measurement: "°"
  icon: mdi:thermometer

thermostat_parents:
  name: Confort
  min: 15
  max: 25
  step: 1
  mode: box
  unit_of_measurement: "°"
  icon: mdi:thermometer

thermostat_consigne_parents:
  name: Consigne
  min: 15
  max: 25
  step: 1
  mode: box
  unit_of_measurement: "°"
  icon: mdi:thermometer

thermostat_thea:
  name: Confort
  min: 15
  max: 25
  step: 1
  mode: box
  unit_of_measurement: "°"
  icon: mdi:thermometer

thermostat_consigne_thea:
  name: Consigne
  min: 15
  max: 25
  step: 1
  mode: box
  unit_of_measurement: "°"
  icon: mdi:thermometer

