---

##################################
## MQTT - SONOFF
- platform: mqtt
  name: "Sonoff Salon"
  state_topic: "stat/sonoffsalon/POWER"
  command_topic: "cmnd/sonoffsalon/POWER"
  availability_topic: "tele/sonoffsalon/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true

- platform: mqtt
  name: "Sonoff Garage/Portail"
  state_topic: "stat/sonoffgarage/POWER1"
  command_topic: "cmnd/sonoffgarage/POWER1"
  availability_topic: "tele/sonoffgarage/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true

- platform: mqtt
  name: "Sonoff Jardin 1"
  state_topic: "stat/sonoffjardin/POWER1"
  command_topic: "cmnd/sonoffjardin/POWER1"
  availability_topic: "tele/sonoffjardin/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true

##################################
## BROADLINK
- platform: broadlink
  host: !secret broadlink_host
  mac: '49:1D:A1:0D:43:B4'
  timeout: 15
  friendly_name: 'Broadlink'
  type: rm2
  switches:
    comfee:
      friendly_name: "PAC - 26 Auto"
      command_on: 'JgDKAJKOEzYSERI2EjUSEhISEjUTEhISEzMTEhITETUSNRQQEzUSERMSEhISNRM1EjUUNRI0FDMTNRM0FREREhMRERMREhM1EzUSEhE2EjUTERITERISERQQEzUSExETEzMTNRI2EqyQjhUzExESNhI2EhETERQzEhITERQ0EhETERM0EzUUERE2EhETERMREzUSNRM0EzUTNBM2EjQUNBMREhMRERMRExEUNBI1FBATNRQ0EhESExESEhITERI1ExESEhM0FDQSNRMADQUAAAAAAAAAAAAAAAAAAA=='
      command_off: 'JgDKAJGPEjUUDxM1FDMTEhIRFTMSEhIRFDQTERMREzQTNRMREjYSERUzEzUSNhI0FBESNRI1FTQTERIREhMSEBYyFBAUEBQzFDQTNRMQFBAUEBQPExEUERIRExISNBM1EzQUNBM1EquSjhM1EhETNhI1FA8UEhE1EhISEhI1ExISEhE1EzUTERQzFBESNRI1EzUTNRISEjUSNhI0ExISEhISEhISNBQSEhATNhE1FDQTERIRFBITDxQQExESEhIREzUTNBM1FDMTNRMADQUAAAAAAAAAAAAAAAAAAA=='
