---

- alias: Allumer diffuseur moustiques
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.enable_mosquito_switch
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_salon

- alias: Eteindre diffuseur moustiques
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.enable_mosquito_switch
      state: 'on'    
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_salon
