---
- alias: Démarrage HomeAssistant
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffgarage/power1
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffsalon/power
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffjardin/power1
      payload: ''

- alias: Démarrage Z-Wave
  trigger:
    - platform: event
      event_type: zwave.network_ready
  action:
    - delay: '00:01:00'
    # request all thermostats to set to Confort
    - service: input_select.select_option
      data: 
        entity_id: input_select.radiator_parents,input_select.radiator_thea,input_select.radiator_salon,input_select.radiator_sallemanger
        option: 'Confort'
    - delay: '00:00:10'
    # wait a bit and request an update of all thermostats
    - event: THERMOSTAT_UPDATE
