---

###############################################################
## Gestion radiateur - maintien température à la consigne - RDC

- alias: Thermostat On - Rez de chaussée
  trigger:
  - platform: template
    value_template: "{{ (states('sensor.oregontemp_2340_temp') | float) < ((states('input_number.thermostat_consigne_rdc') | float) - (0.1 | float)) }}"
  - platform: state
    entity_id: input_select.thermostat_mode
  - platform: event
    event_type: THERMOSTAT_UPDATE
  condition:
    - condition: template
      value_template: "{{ (states('sensor.oregontemp_2340_temp') | float) < ((states('input_number.thermostat_consigne_rdc') | float) - (0.1 | float)) }}"
    - condition: template
      value_template: "{{ not is_state('input_select.thermostat_mode', 'Arrêt') }}"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.radiator_salon, input_select.radiator_sallemanger
      option: 'Confort'

- alias: Thermostat Off - Rez de chaussée
  trigger:
  - platform: template
    value_template: "{{ (states('sensor.oregontemp_2340_temp') | float) >  ((states('input_number.thermostat_consigne_rdc') | float) + (0.1 | float)) }}"
  - platform: state
    entity_id: input_select.thermostat_mode
  - platform: event
    event_type: THERMOSTAT_UPDATE
  condition:
    - condition: template
      value_template: "{{ (states('sensor.oregontemp_2340_temp') | float) > ((states('input_number.thermostat_consigne_rdc') | float) + (0.1 | float)) }}"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.radiator_salon, input_select.radiator_sallemanger
      option: 'Arrêt'

######################################################################
## Gestion radiateur - maintien température à la consigne - Ch. Parent

- alias: Thermostat On - Chambre Parents
  trigger:
  - platform: template
    value_template: "{{ (states('sensor.oregontemphygro_5288a_temp') | float) < ((states('input_number.thermostat_consigne_parents') | float) - (0.1 | float)) }}"
  - platform: state
    entity_id: input_select.thermostat_mode
  - platform: event
    event_type: THERMOSTAT_UPDATE
  condition:
    - condition: template
      value_template: "{{ (states('sensor.oregontemphygro_5288a_temp') | float) < ((states('input_number.thermostat_consigne_parents') | float) - (0.1 | float)) }}"
    - condition: template
      value_template: "{{ not is_state('input_select.thermostat_mode', 'Arrêt') }}"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.radiator_parents
      option: 'Confort'

- alias: Thermostat Off - Chambre Parents
  trigger:
  - platform: template
    value_template: "{{ (states('sensor.oregontemphygro_5288a_temp') | float) > ((states('input_number.thermostat_consigne_parents') | float) + (0.1 | float)) }}"
  - platform: state
    entity_id: input_select.thermostat_mode
  - platform: event
    event_type: THERMOSTAT_UPDATE
  condition:
    - condition: template
      value_template: "{{ (states('sensor.oregontemphygro_5288a_temp') | float) > ((states('input_number.thermostat_consigne_parents') | float) + (0.1 | float)) }}"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.radiator_parents
      option: 'Arrêt'

####################################################################
## Gestion radiateur - maintien température à la consigne - Ch. Théa

- alias: Thermostat On - Chambre Théa
  trigger:
  - platform: template
    value_template: "{{ (states('sensor.oregontemphygro_628da_temp') | float) < ((states('input_number.thermostat_consigne_thea') | float) - (0.1 | float)) }}"
  - platform: state
    entity_id: input_select.thermostat_mode
  - platform: event
    event_type: THERMOSTAT_UPDATE
  condition:
    - condition: template
      value_template: "{{ (states('sensor.oregontemphygro_628da_temp') | float) < ((states('input_number.thermostat_consigne_thea') | float) - (0.1 | float)) }}"
    - condition: template
      value_template: "{{ not is_state('input_select.thermostat_mode', 'Arrêt') }}"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.radiator_thea
      option: 'Confort'

- alias: Thermostat Off - Chambre Théa
  trigger:
  - platform: template
    value_template: "{{ (states('sensor.oregontemphygro_628da_temp') | float) > ((states('input_number.thermostat_consigne_thea') | float) + (0.1 | float)) }}"
  - platform: state
    entity_id: input_select.thermostat_mode
  - platform: event
    event_type: THERMOSTAT_UPDATE
  condition:
    - condition: template
      value_template: "{{ (states('sensor.oregontemphygro_628da_temp') | float) > ((states('input_number.thermostat_consigne_thea') | float) + (0.1 | float)) }}"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.radiator_thea
      option: 'Arrêt'
