---

- alias: Ouverture automatique des volets
  trigger:
    - platform: sun
      event: sunrise
    - platform: time
      at: '07:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_covers_sunrise
        state: 'on'
      - condition: time
        after: '07:00:00'
      - condition: sun  
        after: sunrise
  action:
    - service: cover.set_cover_position
      entity_id: cover.fibaro_roller_shutter_cuisine_level
      data:
        position: 100

- alias: Fermeture automatique des volets
  trigger:
    - platform: sun
      event: sunset
    - platform: time
      at: '18:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.enable_covers_sunset
        state: 'on'
      - condition: time
        after: '18:00:00'
      - condition: sun  
        after: sunset
  action:
    - service: shell_command.alexa_say
      data:
        device: "echo"
        text: "attention je vais procéder à la fermeture des volets dans deux minutes !"
    - service: shell_command.alexa_say
      data:
        device: "echo-dot"
        text: "attention je vais procéder à la fermeture des volets dans deux minutes !"
    - delay: '00:02:00'
    - service: shell_command.alexa_say
      data:
        device: "echo"
        text: 'fermeture des volets'
    - service: shell_command.alexa_say
      data:
        device: "echo-dot"
        text: 'fermeture des volets'
    - service: cover.set_cover_position
      entity_id: cover.fibaro_roller_shutter_cuisine_level, cover.fibaro_roller_shutter_salle_a_manger_level
      data:
        position: 0
    - service: cover.set_cover_position
      entity_id: cover.fibaro_roller_shutter_salon_level
      data:
        position: 30
