version: '2'

services:
  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    restart: always
    ports:
      - "5556:80"
    volumes:
      - /srv/disk1/docker-data/data/tasmoadmin:/data 
    logging:
      options:
        max-size: 10m

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2021.9.7
    restart: always
    user: 0:1000
    ports:
      - "8123:8123"
    volumes:
      - /srv/disk1/docker-data/data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 10m

  nodered:
    container_name: nodered
    image: my-nodered:1.2.9
    restart: always
    user: 1000:1000
    ports:
      - "1880:1880"
    volumes:
      - /srv/disk1/docker-data/data/nodered:/data
      - /etc/localtime:/etc/localtime:ro
      - /srv/disk1/docker-data/data/nodered/gammu-smsdrc.conf:/etc/gammu-smsdrc:ro
    environment:
      - TZ=Europe/Paris
      - FLOWS=my_flows.json
    devices:
      - /dev/hspa_modem:/dev/hspa
    logging:
      options:
        max-size: 10m

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.19.1
    restart: always
    volumes:
      - /srv/disk1/docker-data/data/zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/zigbee2:/dev/zigbee
    ports:
      - 8090:8080
    environment:
      TIMEZONE: Europe/Paris    
    logging:
      options:
        max-size: 10m

  rflink2mqtt:
    container_name: rflink2mqtt
    image: rflink2mqtt:0.9.4
    restart: always
    volumes:
      - /srv/disk1/docker-data/data/rflink2mqtt:/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/rflink:/dev/rflink
    environment:
      TIMEZONE: Europe/Paris
      LOG_LEVEL: INFO
    logging:
      options:
        max-size: 10m

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:5.6.2
    restart: unless-stopped
    devices:
      - /dev/zwave:/dev/ttyACM0
    ports:
      - "8091:8091"
      - "8092:3000"
    volumes:
      - /srv/disk1/docker-data/data/zwavejs2mqtt:/usr/src/app/store
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 10m

