version: '2'

services:
  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    restart: always
    ports:
      - "5556:80"
    volumes:
      - //srv/disk1/docker-data/data/tasmoadmin:/data 
    logging:
      options:
        max-size: 10m
 
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - /srv/disk1/docker-data/data/influxdb:/var/lib/influxdb
    logging:
      options:
        max-size: 10m

  homeassistant:
    container_name: hass
    # use cutom image with own dependencies
    image: my-homeassistant:0.88.2
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - /srv/disk1/docker-data/data/homeassistant:/config
      - /srv/disk1/docker-data/data/homeassistant/options.xml:/usr/local/lib/python3.6/site-packages/python_openzwave/ozw_config/options.xml
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/rflink:/dev/rflink
      - /dev/zwave:/dev/zwave
      - /dev/zigbee:/dev/zigbee
    logging:
      options:
        max-size: 10m

  appdaemon:
    container_name: appdaemon
    # use cutom image with own dependencies
    image: my-appdaemon:latest
    restart: always
    volumes:
      - /srv/disk1/docker-data/data/appdaemon/gammu-smsdrc.conf:/etc/gammu-smsdrc:ro
      - /etc/localtime:/etc/localtime:ro
      - /srv/disk1/docker-data/data/appdaemon/data:/conf
      - /srv/disk1/docker-data/data/homeassistant:/confhass
    devices:
      - /dev/hspa:/dev/hspa
    logging:
      options:
        max-size: 10m

  nodered:
    container_name: nodered
    image: nodered/node-red-docker:v8
    restart: always
    user: 1000:1000
    ports:
      - "1880:1880"
    volumes:
      - /srv/disk1/docker-data/data/nodered:/data
    environment:
      - TZ="Europe/Paris"
      - FLOWS="my_flows.json"
    logging:
      options:
        max-size: 10m

