version: '2'

services:
  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    restart: always
    ports:
      - "5556:80"
    volumes:
      - /srv/disk1/docker-data/data/tasmoadmin:/data 
    logging:
      options:
        max-size: 10m
 
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - /srv/disk1/docker-data/data/influxdb:/var/lib/influxdb
    logging:
      options:
        max-size: 10m

  homeassistant:
    container_name: hass
    image: homeassistant/home-assistant:0.99.3
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - /srv/disk1/docker-data/data/homeassistant:/config
      - /srv/disk1/docker-data/data/homeassistant/options.xml:/usr/local/lib/python3.6/site-packages/python_openzwave/ozw_config/options.xml
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/rflink:/dev/rflink
      - /dev/zwave:/dev/zwave
    logging:
      options:
        max-size: 10m

  appdaemon:
    container_name: appdaemon
    # use cutom image with own dependencies
    image: my-appdaemon:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/disk1/docker-data/data/appdaemon/data:/conf
    logging:
      options:
        max-size: 10m

  nodered:
    container_name: nodered
    image: my-nodered:latest
    restart: always
    user: 1000:1000
    ports:
      - "1880:1880"
    volumes:
      - /srv/disk1/docker-data/data/nodered:/data
      - /etc/localtime:/etc/localtime:ro
      - /srv/disk1/docker-data/data/nodered/gammu-smsdrc.conf:/etc/gammu-smsdrc:ro
    environment:
      - TZ=Europe/Paris
      - FLOWS=my_flows.json
    devices:
      - /dev/hspa:/dev/hspa
    logging:
      options:
        max-size: 10m

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: always
    volumes:
      - /srv/disk1/docker-data/data/zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/zigbee2:/dev/zigbee
    environment:
      TIMEZONE: Europe/Paris    
    logging:
      options:
        max-size: 10m

  zigbee2mqttassistant:
    container_name: zigbee2mqttassistant
    image: carldebilly/zigbee2mqttassistant
    restart: always
    ports:
      - 8080:80
    environment:
      Z2MA_SETTINGS__MQTTSERVER: 192.168.254.220
      Z2MA_SETTINGS__MQTTUSERNAME: hass
      Z2MA_SETTINGS__MQTTPASSWORD: Wjy9SYTe3oH5
      TIMEZONE: Europe/Paris    
    logging:
      options:
        max-size: 10m
