version: '2'

services:
  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    restart: always
    ports:
      - "5556:80"
    volumes:
      - /srv/disk1/docker-data/data/tasmoadmin:/data 
    logging:
      options:
        max-size: 10m

#  homeassistant:
#    container_name: homeassistant
#    image: homeassistant/home-assistant:0.111.4
#    restart: always
#    ports:
#      - "8124:8123"
#    volumes:
#      - /srv/disk1/docker-data/data/homeassistant_old:/config
#      - /srv/disk1/docker-data/data/homeassistant_old/options.xml:/usr/local/lib/python3.6/site-packages/python_openzwave/ozw_config/options.xml
#      - /etc/localtime:/etc/localtime:ro
#    devices:
#      - /dev/zwave:/dev/zwave
#    logging:
#      options:
#        max-size: 10m

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2020.12.1
    restart: always
    user: 0:1000
    ports:
      - "8123:8123"
    volumes:
      - /srv/disk1/docker-data/data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 10m

  nodered:
    container_name: nodered
    image: my-nodered:1.0.6
    restart: always
    user: 1000:1000
    ports:
      - "1880:1880"
    volumes:
      - /srv/disk1/docker-data/data/nodered:/data
      - /etc/localtime:/etc/localtime:ro
      - /srv/disk1/docker-data/data/nodered/gammu-smsdrc.conf:/etc/gammu-smsdrc:ro
    environment:
      - TZ=Europe/Paris
      - FLOWS=my_flows.json
    devices:
      - /dev/hspa_modem:/dev/hspa
    logging:
      options:
        max-size: 10m

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.15.0
    restart: always
    volumes:
      - /srv/disk1/docker-data/data/zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/zigbee2:/dev/zigbee
    ports:
      - 8090:8080
    environment:
      TIMEZONE: Europe/Paris    
    logging:
      options:
        max-size: 10m

  rflink2mqtt:
    container_name: rflink2mqtt
    image: rflink2mqtt:0.8.6
    restart: always
    volumes:
      - /srv/disk1/docker-data/data/rflink2mqtt:/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/rflink:/dev/rflink
    environment:
      TIMEZONE: Europe/Paris
      LOG_LEVEL: INFO
    logging:
      options:
        max-size: 10m

#  ble2mqtt:
#    container_name: ble2mqtt
#    image: ble2mqtt
#    restart: always
#    network_mode: host
#    volumes:
#      - /srv/disk1/docker-data/data/ble2mqtt:/data
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      TIMEZONE: Europe/Paris
#    logging:
#      options:
#        max-size: 10m

  ozwd:
    image: openzwave/ozwdaemon:allinone-latest
    container_name: ozwd
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/zwave:/dev/ttyUSB0
    volumes:
      - /srv/disk1/docker-data/data/ozw:/opt/ozw/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1983:1983"
      - "5901:5901"
      - "7800:7800"
    environment:
      MQTT_SERVER: "192.168.254.220"
      MQTT_PORT: "1883"
      MQTT_USERNAME: "hass"
      MQTT_PASSWORD: "Wjy9SYTe3oH5"
      USB_PATH: "/dev/ttyUSB0"
      OZW_NETWORK_KEY: "0x2D,0xA6,0xCC,0xDC,0xD3,0x3D,0xEF,0x1C,0x9D,0xD5,0x89,0x3C,0x43,0x78,0xAD,0xF6"
    restart: unless-stopped
    