version: '2'

services:
  tasmoadmin:
    container_name: tasmoadmin
    image: ghcr.io/tasmoadmin/tasmoadmin:v1.8.0-alpine-amd64
    restart: unless-stopped
    ports:
      - "5556:80"
    volumes:
      - /srv/disk1/docker-data/data/tasmoadmin:/data 
    logging:
      options:
        max-size: 10m

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2022.11.5
    restart: unless-stopped
    user: 0:1000
    ports:
      - "5683:5683"
      - "8123:8123"
    volumes:
      - /srv/disk1/docker-data/data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/hspa_modem:/dev/hspa
    logging:
      options:
        max-size: 10m

  nodered:
    container_name: nodered
    image: nodered/node-red:3.0.2
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "1880:1880"
    volumes:
      - /srv/disk1/docker-data/data/nodered:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris
      - FLOWS=my_flows.json
    logging:
      options:
        max-size: 10m

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.27.2
    restart: unless-stopped
    volumes:
      - /srv/disk1/docker-data/data/zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/zigbee2:/dev/zigbee
    ports:
      - 8090:8080
    environment:
      TIMEZONE: Europe/Paris    
    logging:
      options:
        max-size: 10m

  rflink2mqtt:
    container_name: rflink2mqtt
    image: rflink2mqtt:0.9.5
#    image: rflink:latest
    restart: unless-stopped
    volumes:
      - /srv/disk1/docker-data/data/rflink2mqtt:/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/rflink:/dev/rflink
    environment:
      TIMEZONE: Europe/Paris
      LOG_LEVEL: INFO
    logging:
      options:
        max-size: 10m

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwave-js-ui:8.5.1
    restart: unless-stopped
    devices:
      - /dev/zwave:/dev/ttyACM0
    ports:
      - "8091:8091"
      - "8092:3000"
    volumes:
      - /srv/disk1/docker-data/data/zwavejs2mqtt:/usr/src/app/store
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 10m

  tileboard:
    container_name: tileboard
    image: tileboard/tileboard:2.10.2
    restart: unless-stopped
    ports:
      - "8094:80"
    volumes:
      - /srv/disk1/docker-data/data/tileboard/config.js:/usr/share/nginx/html/config.js
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: 10m

